name: Test Project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Begins
        run: echo "Getting started"
      - name: Get Code
        uses: actions/checkout@V3
      - name: Install Node JS
        uses: actions/setup-node@v3
        with:
            node-version: 18
      - name: Install Dependencies or npm install
        run: npm ci
      - name: Run tests
        run: npm test

